/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether the process is responding */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check PostgreSQL connectivity and initial schema availability */
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemStatus: components["schemas"]["ReadySystem"] | components["schemas"]["UnavailableSystem"];
        ReadySystem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "ready";
            /** @enum {string} */
            database: "ready";
            /** @enum {string} */
            environment: "simulation";
            /** @enum {boolean} */
            advancedAiEnabled: false;
        };
        UnavailableSystem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "unavailable";
            /** @enum {string} */
            database: "unavailable";
            /** @enum {string} */
            environment: "simulation";
            /** @enum {boolean} */
            advancedAiEnabled: false;
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "INVALID_REQUEST" | "NOT_FOUND" | "ORIGIN_NOT_ALLOWED" | "INTERNAL_ERROR";
                message: string;
                requestId: string;
            };
        };
    };
    responses: {
        /** @description Safe request error. The server generates a fresh X-Request-Id and never reflects request metadata. */
        RequestError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is live. Database availability is checked separately. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                    };
                };
            };
            400: components["responses"]["RequestError"];
            403: components["responses"]["RequestError"];
            500: components["responses"]["RequestError"];
        };
    };
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database and initial schema are available. No product feature readiness is implied. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadySystem"];
                };
            };
            400: components["responses"]["RequestError"];
            403: components["responses"]["RequestError"];
            500: components["responses"]["RequestError"];
            /** @description Database or initial schema unavailable. Contains no connection details. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnavailableSystem"];
                };
            };
        };
    };
}
